version: '3.8'

services:
  ghost:
    build: .
    restart: always
    ports:
      - "2368:2368"
    environment:
      # Basic Ghost Configuration
      NODE_ENV: production
      url: ${GHOST_URL:-http://localhost:2368}
      
      # Database Configuration (PostgreSQL via Neon)
      database__client: pg
      database__connection__connectionString: ${DATABASE_URL}
      
      # Cloudinary Configuration
      storage__active: cloudinary
      storage__cloudinary__cloud_name: ${CLOUDINARY_CLOUD_NAME}
      storage__cloudinary__api_key: ${CLOUDINARY_API_KEY}
      storage__cloudinary__api_secret: ${CLOUDINARY_API_SECRET}
      storage__cloudinary__secure: ${CLOUDINARY_SECURE:-true}
      
      # Mail Configuration (Mailgun)
      mail__transport: SMTP
      mail__options__service: Mailgun
      mail__options__host: ${MAILGUN_SMTP_SERVER:-smtp.mailgun.org}
      mail__options__port: ${MAILGUN_SMTP_PORT:-587}
      mail__options__auth__user: ${MAILGUN_SMTP_LOGIN}
      mail__options__auth__pass: ${MAILGUN_SMTP_PASSWORD}
      mail__from: ${GHOST_FROM_EMAIL}
      
      # ActivityPub Configuration
      activitypub__enabled: true
      activitypub__url: ${ACTIVITYPUB_URL}
      
      # Analytics Configuration
      analytics__enabled: true
      
    volumes:
      - ghost_content:/var/lib/ghost/content
      - ghost_logs:/var/lib/ghost/logs
    networks:
      - ghost-network

volumes:
  ghost_content:
  ghost_logs:

networks:
  ghost-network:
    driver: bridge