version: '3.8'

services:
  ghost:
    image: ghost:6-alpine
    restart: always
    ports:
      - "2368:2368"
    environment:
      # Basic Ghost Configuration
      NODE_ENV: production
      url: ${GHOST_URL:-http://localhost:2368}
      
      # Database Configuration
      database__client: mysql
      database__connection__host: ${DATABASE_HOST:-db}
      database__connection__user: ${DATABASE_USER:-ghost}
      database__connection__password: ${DATABASE_PASSWORD:-ghostpassword}
      database__connection__database: ${DATABASE_NAME:-ghost}
      
      # Mail Configuration (Mailgun)
      mail__transport: SMTP
      mail__options__service: Mailgun
      mail__options__host: ${MAILGUN_SMTP_SERVER:-smtp.mailgun.org}
      mail__options__port: ${MAILGUN_SMTP_PORT:-587}
      mail__options__auth__user: ${MAILGUN_SMTP_LOGIN}
      mail__options__auth__pass: ${MAILGUN_SMTP_PASSWORD}
      mail__from: ${GHOST_FROM_EMAIL}
      
      # ActivityPub Configuration
      activitypub__enabled: true
      activitypub__url: ${ACTIVITYPUB_URL}
      
      # Analytics Configuration
      analytics__enabled: true
      
      # Storage Configuration
      storage__active: local
      storage__local__path: /var/lib/ghost/content/
      
    volumes:
      - ghost_content:/var/lib/ghost/content
      - ghost_logs:/var/lib/ghost/logs
    depends_on:
      - db
    networks:
      - ghost-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DATABASE_NAME:-ghost}
      MYSQL_USER: ${DATABASE_USER:-ghost}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-ghostpassword}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ghost-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  ghost_content:
  ghost_logs:
  db_data:

networks:
  ghost-network:
    driver: bridge