services:
  # Ghost CMS Service
  - type: web
    name: ghost-pro-6
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /ghost/api/v4/admin/site/
    envVars:
      - key: NODE_ENV
        value: production
      - key: url
        fromService:
          type: web
          name: ghost-pro-6
          property: host
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_EOVrRDdH23Sb@ep-quiet-hall-a1ovs2pc-pooler.ap-southeast-1.aws.neon.tech/ghost_production?sslmode=require&channel_binding=require
      - key: CLOUDINARY_CLOUD_NAME
        value: dptbffnce
      - key: CLOUDINARY_API_KEY
        value: 692547711148446
      - key: CLOUDINARY_API_SECRET
        value: 6Yv_tSglN4uOY6KyS1wQWpv2bXI
      - key: CLOUDINARY_SECURE
        value: true
      - key: mail__transport
        value: SMTP
      - key: mail__options__service
        value: Mailgun
      - key: mail__options__host
        value: smtp.mailgun.org
      - key: mail__options__port
        value: 587
      - key: mail__options__auth__user
        sync: false
      - key: mail__options__auth__pass
        sync: false
      - key: mail__from
        sync: false
      - key: activitypub__enabled
        value: true
      - key: analytics__enabled
        value: true
      - key: storage__active
        value: local